In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv(r"C:\Users\Admin\Desktop\data\mushrooms.csv")

In [3]:
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color   ...   stalk-surface-below-ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [4]:
df.isnull().sum().sum()

0

In [5]:
df.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill-spacing gill-size gill-color   ...   stalk-surface-below-ring  \
count          8124      8124       8124   ...                       8124   
unique            2         2         12   ...                          4   
top               c         b          b   ...                          s   
freq           6812      5612       1728   ...                       4936   

       stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

In [6]:
#dependent is class column and other are independent

In [7]:
x=df.drop(['class'],axis=1)
y=df['class']

In [8]:
x.head()

cap-shape cap-surface cap-color bruises odor gill-attachment gill-spacing  \
0         x           s         n       t    p               f            c   
1         x           s         y       t    a               f            c   
2         b           s         w       t    l               f            c   
3         x           y         w       t    p               f            c   
4         x           s         g       f    n               f            w   

  gill-size gill-color stalk-shape   ...   stalk-surface-below-ring  \
0         n          k           e   ...                          s   
1         b          k           e   ...                          s   
2         b          n           e   ...                          s   
3         n          n           e   ...                          s   
4         b          k           t   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 22 columns]

In [9]:
# converting categorical data into dummy

In [10]:
x=pd.get_dummies(x,columns=x.columns,drop_first=True)

In [11]:
x.head()

cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  cap-shape_x  \
0            0            0            0            0            1   
1            0            0            0            0            1   
2            0            0            0            0            0   
3            0            0            0            0            1   
4            0            0            0            0            1   

   cap-surface_g  cap-surface_s  cap-surface_y  cap-color_c  cap-color_e  \
0              0              1              0            0            0   
1              0              1              0            0            0   
2              0              1              0            0            0   
3              0              0              1            0            0   
4              0              1              0            0            0   

     ...      population_n  population_s  population_v  population_y  \
0    ...                 0             1             0             0   
1    ...                 1             0             0             0   
2    ...                 1             0             0             0   
3    ...                 0             1             0             0   
4    ...                 0             0             0             0   

   habitat_g  habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0          0          0          0          0          1          0  
1          1          0          0          0          0          0  
2          0          0          1          0          0          0  
3          0          0          0          0          1          0  
4          1          0          0          0          0          0  

[5 rows x 95 columns]

In [12]:
# splitting the data
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=1)

In [13]:
#feature scaling
from sklearn.preprocessing import StandardScaler

In [14]:
sc=StandardScaler()

In [15]:
xtrain=sc.fit_transform(xtrain)
xtest=sc.fit_transform(xtest)

F:\anaconda\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype uint8 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
F:\anaconda\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype uint8 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
F:\anaconda\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype uint8 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
F:\anaconda\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype uint8 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [16]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)

xtrain=pca.fit_transform(xtrain)
xtest=pca.transform(xtest)

In [17]:
from sklearn.linear_model import LogisticRegression
classy=LogisticRegression()


In [18]:
classy.fit(xtrain,ytrain)

F:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [19]:
y_pred=classy.predict(xtest)

In [20]:
from sklearn.metrics import confusion_matrix,classification_report
cm=confusion_matrix(ytest,y_pred)

In [21]:
cm

array([[1202,   34],
       [ 196, 1006]], dtype=int64)

In [22]:
print(classification_report(ytest,y_pred))

              precision    recall  f1-score   support

           e       0.86      0.97      0.91      1236
           p       0.97      0.84      0.90      1202

   micro avg       0.91      0.91      0.91      2438
   macro avg       0.91      0.90      0.91      2438
weighted avg       0.91      0.91      0.91      2438



In [23]:
## applying knn algorithum


In [24]:
from sklearn.neighbors import KNeighborsClassifier as KNN
classifier=KNN()


In [25]:
classifier.fit(xtrain,ytrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [26]:
y_pred=classifier.predict(xtest)

In [27]:
from sklearn.metrics import accuracy_score

In [28]:
accuracy_score(ytest,y_pred)

0.9216570959803118

In [56]:
print(classification_report(ytest,y_pred))

              precision    recall  f1-score   support

           e       0.91      0.94      0.92      1236
           p       0.94      0.90      0.92      1202

   micro avg       0.92      0.92      0.92      2438
   macro avg       0.92      0.92      0.92      2438
weighted avg       0.92      0.92      0.92      2438



In [29]:
## applying svc(support vector classification)

In [30]:
from sklearn.svm import SVC
classy=SVC(kernel='rbf',random_state=1)

In [31]:
classy.fit(xtrain,ytrain)

F:\anaconda\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=1,
  shrinking=True, tol=0.001, verbose=False)

In [32]:
pred=classy.predict(xtest)

In [33]:
accuracy_score(ytest,pred)

0.9294503691550451

In [34]:
cm=confusion_matrix(ytest,pred)

In [55]:
print(classification_report(ytest,pred))

              precision    recall  f1-score   support

           e       0.89      0.98      0.93      1236
           p       0.98      0.88      0.92      1202

   micro avg       0.93      0.93      0.93      2438
   macro avg       0.93      0.93      0.93      2438
weighted avg       0.93      0.93      0.93      2438



In [35]:
cm

array([[1209,   27],
       [ 145, 1057]], dtype=int64)

In [36]:
## applying the Decision tree

In [49]:
from sklearn.tree import DecisionTreeClassifier as DT
c=DT(criterion='entropy',random_state=1)

In [50]:
c.fit(xtrain,ytrain)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=1,
            splitter='best')

In [51]:
prd=c.predict(xtest)

In [67]:
c.score(xtrain,ytrain)

1.0

In [52]:
accuracy_score(ytest,prd)

0.8835110746513536

In [53]:
cm=confusion_matrix(ytest,prd)

In [54]:
from sklearn.metrics import classification_report
print(classification_report(ytest,prd))

              precision    recall  f1-score   support

           e       0.88      0.89      0.89      1236
           p       0.88      0.88      0.88      1202

   micro avg       0.88      0.88      0.88      2438
   macro avg       0.88      0.88      0.88      2438
weighted avg       0.88      0.88      0.88      2438



In [42]:
cm

array([[1096,  140],
       [ 144, 1058]], dtype=int64)

In [43]:
## applying Naive_bayes


In [44]:
from sklearn.naive_bayes import GaussianNB as NB
classy=NB()
classy.fit(xtrain,ytrain)

GaussianNB(priors=None, var_smoothing=1e-09)

In [45]:
predt=classy.predict(xtest)

In [47]:
from sklearn.metrics import confusion_matrix,classification_report
cm=confusion_matrix(ytest,predt)

In [66]:
classy.score(xtrain,ytrain)

0.8951811466760464

In [48]:
print(classification_report(ytest,predt))

              precision    recall  f1-score   support

           e       0.85      0.97      0.91      1236
           p       0.97      0.83      0.89      1202

   micro avg       0.90      0.90      0.90      2438
   macro avg       0.91      0.90      0.90      2438
weighted avg       0.91      0.90      0.90      2438



In [57]:
## applying Random forest


In [58]:
from sklearn.ensemble import RandomForestClassifier
a=RandomForestClassifier(n_estimators=50,criterion='entropy',random_state=1)


In [59]:
a.fit(xtrain,ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=None,
            oob_score=False, random_state=1, verbose=0, warm_start=False)

In [60]:
prediction=a.predict(xtest)

In [61]:
from sklearn.metrics import classification_report
print(classification_report(ytest,prediction))

              precision    recall  f1-score   support

           e       0.90      0.95      0.92      1236
           p       0.94      0.89      0.92      1202

   micro avg       0.92      0.92      0.92      2438
   macro avg       0.92      0.92      0.92      2438
weighted avg       0.92      0.92      0.92      2438



In [62]:
accuracy_score(ytest,prediction)

0.9204265791632485

In [63]:
cm=confusion_matrix(ytest,prediction)

In [64]:
cm

array([[1170,   66],
       [ 128, 1074]], dtype=int64)

In [65]:
a.score(xtrain,ytrain)

0.9991206472036581